### PR TITLE
fix cocalc url in preface

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by twjudson** [comment]
Fixed!

**Comment by clayrat** [comment]
@twjudson It still seems to point to `https://coclac.com` on `master`.

**Comment by rbeezer** [comment]
We need to update the public version of the repository, I think.  Likely the fix is in the private repo that also has solutions.

Would you like me to do that, Tom?

**Comment by twjudson** [comment]
That’s exactly where it is.  Yes, can you fix it and then let me know what you did.

Tom

On Jul 10, 2019, at 3:47 PM, Rob Beezer <notifications@github.com<mailto:notifications@github.com>> wrote:

We need to update the public version of the repository, I think. Likely the fix is in the private repo that also has solutions.

Would you like me to do that, Tom?

**Comment by twjudson** [comment]
Please standby.  The fix was pushed to a private copy of the repo.  The public master still needs to be updated.


On Jul 10, 2019, at 3:15 PM, Alex Gryzlov <notifications@github.com<mailto:notifications@github.com>> wrote:


@twjudson<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twjudson&d=DwMCaQ&c=2X_btuPRWkGwRX26NHIotzR6MNUgJAbf6yNNV5-qTbU&r=BQmZUphR5rjzEsIGWo4gOhHhb8A_MVZPtDOMQxdFlh8&m=haQgGofPN6t8nd1Qy01wgLgyuj6hXkaLHyqWcT1Np6U&s=jHtLz5fuDfOGLCunrXagP2Dqkl4GBjOJMyvXvI_jYYo&e=> It still seems to point to https://coclac.com on master.

**Pull request closed without merging**
